name: Python CI
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: 3.9}
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install flake8 coverage
      - name: Test
        run: |
          coverage run --source=. manage.py test
          coverage report -m > coverage.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with: {name: test-reports, path: coverage.txt}

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: docker/build-push-action@v3
        with: {context: ., push: false, tags: the-button:latest, load: true}
      
      # 1. Skanowanie TABLE (Tutaj będziemy zmieniać na 1 dla blokowania)
      - name: Trivy Table
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-button:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      
      # 2. Skanowanie JSON
      - name: Trivy JSON
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-button:latest'
          format: 'json'
          output: 'trivy-results.json'
      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with: {name: trivy-results, path: trivy-results.json}

      # 3. Skanowanie SARIF
      - name: Trivy SARIF
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-button:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with: {sarif_file: 'trivy-results.sarif'}
